// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/netty/client/protobuf/message.proto

package com.netty.client.protobuf;

public final class MessageBuf {
  private MessageBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code GAME}
   */
  public enum GAME
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CmdStart = 0;</code>
     */
    CmdStart(0),
    /**
     * <pre>
     * 查看最新版本
     * </pre>
     *
     * <code>G_CMCheckVersion = 1000;</code>
     */
    G_CMCheckVersion(1000),
    /**
     * <pre>
     * 查看公告
     * </pre>
     *
     * <code>G_CMCheckNotice = 1001;</code>
     */
    G_CMCheckNotice(1001),
    /**
     * <pre>
     * 同步服务器的时间
     * </pre>
     *
     * <code>G_CMSyncServerTime = 1002;</code>
     */
    G_CMSyncServerTime(1002),
    /**
     * <pre>
     * 返回最新版本
     * </pre>
     *
     * <code>G_SMCheckVersion = 2001;</code>
     */
    G_SMCheckVersion(2001),
    /**
     * <pre>
     * 返回公告
     * </pre>
     *
     * <code>G_SMCheckNotice = 2002;</code>
     */
    G_SMCheckNotice(2002),
    /**
     * <pre>
     * 返回同步服务器的时间
     * </pre>
     *
     * <code>G_SMSyncServerTime = 2003;</code>
     */
    G_SMSyncServerTime(2003),
    /**
     * <pre>
     * 通知客户端提示语
     * </pre>
     *
     * <code>G_SMNotifyText = 9001;</code>
     */
    G_SMNotifyText(9001),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CmdStart = 0;</code>
     */
    public static final int CmdStart_VALUE = 0;
    /**
     * <pre>
     * 查看最新版本
     * </pre>
     *
     * <code>G_CMCheckVersion = 1000;</code>
     */
    public static final int G_CMCheckVersion_VALUE = 1000;
    /**
     * <pre>
     * 查看公告
     * </pre>
     *
     * <code>G_CMCheckNotice = 1001;</code>
     */
    public static final int G_CMCheckNotice_VALUE = 1001;
    /**
     * <pre>
     * 同步服务器的时间
     * </pre>
     *
     * <code>G_CMSyncServerTime = 1002;</code>
     */
    public static final int G_CMSyncServerTime_VALUE = 1002;
    /**
     * <pre>
     * 返回最新版本
     * </pre>
     *
     * <code>G_SMCheckVersion = 2001;</code>
     */
    public static final int G_SMCheckVersion_VALUE = 2001;
    /**
     * <pre>
     * 返回公告
     * </pre>
     *
     * <code>G_SMCheckNotice = 2002;</code>
     */
    public static final int G_SMCheckNotice_VALUE = 2002;
    /**
     * <pre>
     * 返回同步服务器的时间
     * </pre>
     *
     * <code>G_SMSyncServerTime = 2003;</code>
     */
    public static final int G_SMSyncServerTime_VALUE = 2003;
    /**
     * <pre>
     * 通知客户端提示语
     * </pre>
     *
     * <code>G_SMNotifyText = 9001;</code>
     */
    public static final int G_SMNotifyText_VALUE = 9001;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GAME valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static GAME forNumber(int value) {
      switch (value) {
        case 0: return CmdStart;
        case 1000: return G_CMCheckVersion;
        case 1001: return G_CMCheckNotice;
        case 1002: return G_CMSyncServerTime;
        case 2001: return G_SMCheckVersion;
        case 2002: return G_SMCheckNotice;
        case 2003: return G_SMSyncServerTime;
        case 9001: return G_SMNotifyText;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GAME>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GAME> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GAME>() {
            public GAME findValueByNumber(int number) {
              return GAME.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.netty.client.protobuf.MessageBuf.getDescriptor().getEnumTypes().get(0);
    }

    private static final GAME[] VALUES = values();

    public static GAME valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GAME(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GAME)
  }

  public interface msg_reqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msg_req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息序列号，客户端自增防重
     * </pre>
     *
     * <code>int64 cmd = 1;</code>
     * @return The cmd.
     */
    long getCmd();

    /**
     * <code>int32 messageId = 2;</code>
     * @return The messageId.
     */
    int getMessageId();

    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code msg_req}
   */
  public static final class msg_req extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msg_req)
      msg_reqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use msg_req.newBuilder() to construct.
    private msg_req(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private msg_req() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new msg_req();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private msg_req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              cmd_ = input.readInt64();
              break;
            }
            case 16: {

              messageId_ = input.readInt32();
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netty.client.protobuf.MessageBuf.internal_static_msg_req_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netty.client.protobuf.MessageBuf.internal_static_msg_req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netty.client.protobuf.MessageBuf.msg_req.class, com.netty.client.protobuf.MessageBuf.msg_req.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private long cmd_;
    /**
     * <pre>
     *消息序列号，客户端自增防重
     * </pre>
     *
     * <code>int64 cmd = 1;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public long getCmd() {
      return cmd_;
    }

    public static final int MESSAGEID_FIELD_NUMBER = 2;
    private int messageId_;
    /**
     * <code>int32 messageId = 2;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public int getMessageId() {
      return messageId_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != 0L) {
        output.writeInt64(1, cmd_);
      }
      if (messageId_ != 0) {
        output.writeInt32(2, messageId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, cmd_);
      }
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, messageId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netty.client.protobuf.MessageBuf.msg_req)) {
        return super.equals(obj);
      }
      com.netty.client.protobuf.MessageBuf.msg_req other = (com.netty.client.protobuf.MessageBuf.msg_req) obj;

      if (getCmd()
          != other.getCmd()) return false;
      if (getMessageId()
          != other.getMessageId()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCmd());
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netty.client.protobuf.MessageBuf.msg_req parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_req parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netty.client.protobuf.MessageBuf.msg_req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msg_req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msg_req)
        com.netty.client.protobuf.MessageBuf.msg_reqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty.client.protobuf.MessageBuf.internal_static_msg_req_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty.client.protobuf.MessageBuf.internal_static_msg_req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty.client.protobuf.MessageBuf.msg_req.class, com.netty.client.protobuf.MessageBuf.msg_req.Builder.class);
      }

      // Construct using com.netty.client.protobuf.MessageBuf.msg_req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmd_ = 0L;

        messageId_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netty.client.protobuf.MessageBuf.internal_static_msg_req_descriptor;
      }

      @java.lang.Override
      public com.netty.client.protobuf.MessageBuf.msg_req getDefaultInstanceForType() {
        return com.netty.client.protobuf.MessageBuf.msg_req.getDefaultInstance();
      }

      @java.lang.Override
      public com.netty.client.protobuf.MessageBuf.msg_req build() {
        com.netty.client.protobuf.MessageBuf.msg_req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.netty.client.protobuf.MessageBuf.msg_req buildPartial() {
        com.netty.client.protobuf.MessageBuf.msg_req result = new com.netty.client.protobuf.MessageBuf.msg_req(this);
        result.cmd_ = cmd_;
        result.messageId_ = messageId_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netty.client.protobuf.MessageBuf.msg_req) {
          return mergeFrom((com.netty.client.protobuf.MessageBuf.msg_req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netty.client.protobuf.MessageBuf.msg_req other) {
        if (other == com.netty.client.protobuf.MessageBuf.msg_req.getDefaultInstance()) return this;
        if (other.getCmd() != 0L) {
          setCmd(other.getCmd());
        }
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netty.client.protobuf.MessageBuf.msg_req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netty.client.protobuf.MessageBuf.msg_req) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long cmd_ ;
      /**
       * <pre>
       *消息序列号，客户端自增防重
       * </pre>
       *
       * <code>int64 cmd = 1;</code>
       * @return The cmd.
       */
      @java.lang.Override
      public long getCmd() {
        return cmd_;
      }
      /**
       * <pre>
       *消息序列号，客户端自增防重
       * </pre>
       *
       * <code>int64 cmd = 1;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(long value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息序列号，客户端自增防重
       * </pre>
       *
       * <code>int64 cmd = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = 0L;
        onChanged();
        return this;
      }

      private int messageId_ ;
      /**
       * <code>int32 messageId = 2;</code>
       * @return The messageId.
       */
      @java.lang.Override
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>int32 messageId = 2;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msg_req)
    }

    // @@protoc_insertion_point(class_scope:msg_req)
    private static final com.netty.client.protobuf.MessageBuf.msg_req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netty.client.protobuf.MessageBuf.msg_req();
    }

    public static com.netty.client.protobuf.MessageBuf.msg_req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<msg_req>
        PARSER = new com.google.protobuf.AbstractParser<msg_req>() {
      @java.lang.Override
      public msg_req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new msg_req(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<msg_req> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<msg_req> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.netty.client.protobuf.MessageBuf.msg_req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface msg_rspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msg_rsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 cmd = 1;</code>
     * @return The cmd.
     */
    int getCmd();

    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code msg_rsp}
   */
  public static final class msg_rsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msg_rsp)
      msg_rspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use msg_rsp.newBuilder() to construct.
    private msg_rsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private msg_rsp() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new msg_rsp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private msg_rsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              cmd_ = input.readInt32();
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netty.client.protobuf.MessageBuf.internal_static_msg_rsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netty.client.protobuf.MessageBuf.internal_static_msg_rsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netty.client.protobuf.MessageBuf.msg_rsp.class, com.netty.client.protobuf.MessageBuf.msg_rsp.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>int32 cmd = 1;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public int getCmd() {
      return cmd_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != 0) {
        output.writeInt32(1, cmd_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netty.client.protobuf.MessageBuf.msg_rsp)) {
        return super.equals(obj);
      }
      com.netty.client.protobuf.MessageBuf.msg_rsp other = (com.netty.client.protobuf.MessageBuf.msg_rsp) obj;

      if (getCmd()
          != other.getCmd()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netty.client.protobuf.MessageBuf.msg_rsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_rsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_rsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_rsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_rsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_rsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_rsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_rsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_rsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_rsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_rsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netty.client.protobuf.MessageBuf.msg_rsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netty.client.protobuf.MessageBuf.msg_rsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msg_rsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msg_rsp)
        com.netty.client.protobuf.MessageBuf.msg_rspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty.client.protobuf.MessageBuf.internal_static_msg_rsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty.client.protobuf.MessageBuf.internal_static_msg_rsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty.client.protobuf.MessageBuf.msg_rsp.class, com.netty.client.protobuf.MessageBuf.msg_rsp.Builder.class);
      }

      // Construct using com.netty.client.protobuf.MessageBuf.msg_rsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netty.client.protobuf.MessageBuf.internal_static_msg_rsp_descriptor;
      }

      @java.lang.Override
      public com.netty.client.protobuf.MessageBuf.msg_rsp getDefaultInstanceForType() {
        return com.netty.client.protobuf.MessageBuf.msg_rsp.getDefaultInstance();
      }

      @java.lang.Override
      public com.netty.client.protobuf.MessageBuf.msg_rsp build() {
        com.netty.client.protobuf.MessageBuf.msg_rsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.netty.client.protobuf.MessageBuf.msg_rsp buildPartial() {
        com.netty.client.protobuf.MessageBuf.msg_rsp result = new com.netty.client.protobuf.MessageBuf.msg_rsp(this);
        result.cmd_ = cmd_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netty.client.protobuf.MessageBuf.msg_rsp) {
          return mergeFrom((com.netty.client.protobuf.MessageBuf.msg_rsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netty.client.protobuf.MessageBuf.msg_rsp other) {
        if (other == com.netty.client.protobuf.MessageBuf.msg_rsp.getDefaultInstance()) return this;
        if (other.getCmd() != 0) {
          setCmd(other.getCmd());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netty.client.protobuf.MessageBuf.msg_rsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netty.client.protobuf.MessageBuf.msg_rsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ ;
      /**
       * <code>int32 cmd = 1;</code>
       * @return The cmd.
       */
      @java.lang.Override
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>int32 cmd = 1;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cmd = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msg_rsp)
    }

    // @@protoc_insertion_point(class_scope:msg_rsp)
    private static final com.netty.client.protobuf.MessageBuf.msg_rsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netty.client.protobuf.MessageBuf.msg_rsp();
    }

    public static com.netty.client.protobuf.MessageBuf.msg_rsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<msg_rsp>
        PARSER = new com.google.protobuf.AbstractParser<msg_rsp>() {
      @java.lang.Override
      public msg_rsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new msg_rsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<msg_rsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<msg_rsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.netty.client.protobuf.MessageBuf.msg_rsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_req_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msg_req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_rsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msg_rsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5src/main/java/com/netty/client/protobu" +
      "f/message.proto\"7\n\007msg_req\022\013\n\003cmd\030\001 \001(\003\022" +
      "\021\n\tmessageId\030\002 \001(\005\022\014\n\004data\030\003 \001(\014\"$\n\007msg_" +
      "rsp\022\013\n\003cmd\030\001 \001(\005\022\014\n\004data\030\002 \001(\014*\265\001\n\004GAME\022" +
      "\014\n\010CmdStart\020\000\022\025\n\020G_CMCheckVersion\020\350\007\022\024\n\017" +
      "G_CMCheckNotice\020\351\007\022\027\n\022G_CMSyncServerTime" +
      "\020\352\007\022\025\n\020G_SMCheckVersion\020\321\017\022\024\n\017G_SMCheckN" +
      "otice\020\322\017\022\027\n\022G_SMSyncServerTime\020\323\017\022\023\n\016G_S" +
      "MNotifyText\020\251FB\'\n\031com.netty.client.proto" +
      "bufB\nMessageBufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_msg_req_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msg_req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msg_req_descriptor,
        new java.lang.String[] { "Cmd", "MessageId", "Data", });
    internal_static_msg_rsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_msg_rsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msg_rsp_descriptor,
        new java.lang.String[] { "Cmd", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
